interface DataType {
	id: number;
	page: string;
	quesstion: string;
	answer: string;
}

const faq_data: DataType[] = [
	{
		id: 1,
		page: "home_3",
		quesstion: "What kind of technology does DecentrAgri use to collect real-time farming data?",
		answer: "DecentrAgri deploys a compact multi-sensor field unit equipped with precision-grade probes to measure critical agricultural parameters such as soil pH, moisture levels, ambient sunlight, temperature, and more. These sensors are designed to provide real-time, high-resolution insights tailored for modern farming needs."
	},
	{
		id: 2,
		page: "home_3",
		quesstion: "Is DecentrAgri hardware compatible with all types of farms?",
		answer: "Yes. Our sensor systems are optimized for both smallholder and large-scale farms. Whether you're managing a backyard plot or a commercial plantation, our adaptive hardware can be easily deployed and scaled to your operational needs."
	},
	{
		id: 3,
		page: "home_3",
		quesstion: "How is the collected data processed and used?",
		answer: "Data is transmitted to our AI-powered cloud platform where it's analyzed in real time. The system then provides actionable insights and recommendations, helping farmers make smarter decisions on irrigation, fertilization, and planting strategies."
	},
	{
		id: 4,
		page: "home_3",
		quesstion: "What makes DecentrAgri’s recommendations trustworthy?",
		answer: "All insights generated by DecentrAgri are backed by a blockchain-based verification layer. This ensures complete data transparency and immutability, giving you confidence in every recommendation."
	},
	{
		id: 5,
		page: "home_3",
		quesstion: "Do I need an internet connection for DecentrAgri to work?",
		answer: "While our platform performs best with continuous connectivity, we also support offline data caching and delayed transmission to accommodate remote areas with intermittent internet access."
	},
	{
		id: 6,
		page: "home_3",
		quesstion: "Can DecentrAgri help with sustainability efforts?",
		answer: "Absolutely. By optimizing resource use and minimizing environmental impact, DecentrAgri empowers farmers to adopt sustainable practices without compromising yield or efficiency."
	}
];

export default faq_data;
